[core]
cache_dir = /var/cache/mopidy
data_dir = /var/lib/mopidy

[audio]
output = alsasink device=plughw:CARD=Audio,DEV=0

[http]
enabled = true
hostname = 0.0.0.0
port = 6680

[tidal]
enabled = true
quality = HI_RES_LOSSLESS
login_method = AUTO
auth_method = OAUTH
lazy = false

# playlist_cache_refresh_secs = 0
# playlist_cache_refresh_secs (Optional): Tells if (and how often) playlist content should be refreshed upon lookup.

# 0 (default): The default value (0) means that playlists won't be refreshed after the extension has started, unless they are explicitly modified from mopidy.
# >0: A non-zero value expresses for how long (in seconds) a cached playlist is considered valid. For example, a value of 300 means that the cached snapshot of a playlist will be used if a new lookup occurs within 5 minutes from the previous one, but the playlist will be re-loaded via API if a lookup request occurs later.